# Automatically updated by the winget bot at 2021/Mar/21
Id: IntegrationTests.ManifestUpdate.OneInstallerModify
Version: 1.0
Name: ManifestUpdate Test
Publisher: Contoso
Description: Test manifest update modify
License: Text
Installers:
- Arch: x64
  Url: https://stpkgmanvalwestustest.blob.core.windows.net/test-installers/VSCodeUserSetup-x64-1.46.1.exe
  InstallerType: inno
  Sha256: 6666666666666666666666666666666666666666666666666666666666666666
