# Automatically updated by the winget bot at 2021/Mar/21
Id: IntegrationTests.ManifestUpdate.OneInstallerCreate
Version: 2.0
Name: ManifestUpdate Test
Publisher: Contoso
Description: Manifest update test for Create
License: Text
Installers:
- Arch: x64
  Url: https://stpkgmanvalwestustest.blob.core.windows.net/test-installers/VSCodeUserSetup-x64-1.46.1.exe
  InstallerType: inno
  Sha256: 7777777777777777777777777777777777777777777777777777777777777777
